name: Process Grades

on:
  push:
    paths:
      - "notlar.txt"
      - "grade_calculator.py"
      - "test_grade_calculator.py"

jobs:
  process_grades:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests
      run: |
        python -m unittest test_grade_calculator.py

    - name: Run grade processor
      run: |
        python grade_calculator.py

    - name: Show results
      run: |
        cat sonuclar.txt
